In [1]:
import pandas as pd
import numpy as np

In [2]:
data_df = pd.read_csv('reduced.csv')

In [3]:
#index starts from 1 now
data_df.index = np.arange(1,len(data_df)+1)

### Add cumulative columns

In [4]:
#Adding a new column with the cumulative average of values: reexp1 till Pain
data_df.fillna(value=0, inplace=True)
data_df['Reexp1_cum'] =  data_df['Reexp1'].cumsum()
data_df['Reexp2_cum'] =  data_df['Reexp2'].cumsum()
data_df['Avoid1_cum'] =  data_df['Avoid1'].cumsum()
data_df['Avoid2_cum'] =  data_df['Avoid2'].cumsum()
data_df['NACM1_cum'] =  data_df['NACM1'].cumsum()
data_df['NACM2_cum'] =  data_df['NACM2'].cumsum()
data_df['AAR1_cum'] =  data_df['AAR1'].cumsum()
data_df['AAR2_cum'] =  data_df['AAR2'].cumsum()
data_df['Sleep_cum'] =  data_df['Sleep'].cumsum()
data_df['Pain_cum'] =  data_df['Pain'].cumsum()

In [5]:
c=1;
while(c!=1144):
    i1 = data_df.get_value(c, 'Reexp1_cum', takeable=False)
    data_df.set_value(c, 'Reexp1_cum',i1/c)
    
    i2 = data_df.get_value(c, 'Reexp2_cum', takeable=False)
    data_df.set_value(c, 'Reexp2_cum',i2/c)
    
    i3 = data_df.get_value(c, 'Avoid1_cum', takeable=False)
    data_df.set_value(c, 'Avoid1_cum',i3/c)
    
    
    i4 = data_df.get_value(c, 'Avoid2_cum', takeable=False)
    data_df.set_value(c, 'Avoid2_cum',i4/c)
    
    i5 = data_df.get_value(c, 'NACM1_cum', takeable=False)
    data_df.set_value(c, 'NACM1_cum',i5/c)
    
    i6 = data_df.get_value(c, 'NACM2_cum', takeable=False)
    data_df.set_value(c, 'NACM2_cum',i6/c)
    
    i7 = data_df.get_value(c, 'AAR1_cum', takeable=False)
    data_df.set_value(c, 'AAR1_cum',i7/c)
    
    i8 = data_df.get_value(c, 'AAR2_cum', takeable=False)
    data_df.set_value(c, 'AAR2_cum',i8/c)
    
    i9 = data_df.get_value(c, 'Sleep_cum', takeable=False)
    data_df.set_value(c, 'Sleep_cum',i9/c)
    
    i10 = data_df.get_value(c, 'Pain_cum', takeable=False)
    data_df.set_value(c, 'Pain_cum',i10/c)
    
   
    c = c+1

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  import sys
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  # Remove the CWD from sys.path while we load stuff.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  del sys.path[0]
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:17: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:20: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:22: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:23: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:25: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:26: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:28: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:31: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:32: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

In [6]:
data_df.head()

,PID,PCL.score,PHQ.score,SDS.score,Days.Since,Reexp1,Reexp2,Avoid1,Avoid2,NACM1,...,Reexp1_cum,Reexp2_cum,Avoid1_cum,Avoid2_cum,NACM1_cum,NACM2_cum,AAR1_cum,AAR2_cum,Sleep_cum,Pain_cum
1,202,25.0,7.0,0.0,2.0,2.0,2.500000,3.00,3.000,2.00,...,2.00,2.500000,3.000,3.000000,2.000000,0.0000,0.0,0.500000,0.500000,5.500000
2,202,25.0,7.0,0.0,5.5,1.0,1.250000,0.75,1.125,1.50,...,1.50,1.875000,1.875,2.062500,1.750000,0.3750,0.0,0.250000,0.625000,4.750000
3,202,25.0,7.0,0.0,9.5,0.0,0.500000,0.75,1.000,0.75,...,1.00,1.416667,1.500,1.708333,1.416667,0.2500,0.0,0.250000,0.833333,4.083333
4,202,25.0,7.0,0.0,13.5,0.0,0.333333,0.00,0.000,0.00,...,0.75,1.145833,1.125,1.281250,1.062500,0.1875,0.0,0.270833,0.625000,3.479167
5,202,25.0,7.0,0.0,17.5,0.0,0.000000,0.00,0.000,0.00,...,0.60,0.916667,0.900,1.025000,0.850000,0.1500,0.0,0.216667,0.500000,2.916667

In [7]:
data_df.index = np.arange(1,len(data_df)+1)

In [8]:
data_df.head()

,PID,PCL.score,PHQ.score,SDS.score,Days.Since,Reexp1,Reexp2,Avoid1,Avoid2,NACM1,...,Reexp1_cum,Reexp2_cum,Avoid1_cum,Avoid2_cum,NACM1_cum,NACM2_cum,AAR1_cum,AAR2_cum,Sleep_cum,Pain_cum
1,202,25.0,7.0,0.0,2.0,2.0,2.500000,3.00,3.000,2.00,...,2.00,2.500000,3.000,3.000000,2.000000,0.0000,0.0,0.500000,0.500000,5.500000
2,202,25.0,7.0,0.0,5.5,1.0,1.250000,0.75,1.125,1.50,...,1.50,1.875000,1.875,2.062500,1.750000,0.3750,0.0,0.250000,0.625000,4.750000
3,202,25.0,7.0,0.0,9.5,0.0,0.500000,0.75,1.000,0.75,...,1.00,1.416667,1.500,1.708333,1.416667,0.2500,0.0,0.250000,0.833333,4.083333
4,202,25.0,7.0,0.0,13.5,0.0,0.333333,0.00,0.000,0.00,...,0.75,1.145833,1.125,1.281250,1.062500,0.1875,0.0,0.270833,0.625000,3.479167
5,202,25.0,7.0,0.0,17.5,0.0,0.000000,0.00,0.000,0.00,...,0.60,0.916667,0.900,1.025000,0.850000,0.1500,0.0,0.216667,0.500000,2.916667

In [9]:
#drop HR column
data_df.drop(['HR'] , axis = 1 , inplace = True)

In [10]:
#Adding Threshold column based on ground truth values
data_df['Threshold'] = 0
#replace threhold value with 1 if PCL.score is >10, replace with 0 if PCL.score <= 10 or PCL.score is nan(ex for PID 208) 
data_df.loc[data_df['PCL.score'] >= 11, 'Threshold'] = 1

In [11]:
data_df.to_csv('withcumcol.csv',index=False)

### Added Nan Count and Sympton sum columns

In [12]:
#add Nan count column that has count of total Nans in a row
data_df['Nan_count'] = data_df.isnull().sum(axis=1)

#add symptom sum column which is the sum of all non-Nan values in a row instance
data_df['symptom_sum'] =  data_df['Reexp1']+ data_df['Reexp2']+data_df['Avoid1']+ data_df['Avoid2']+ data_df['NACM1']+ data_df['NACM2']+ data_df['AAR1']+ data_df['AAR2']+ data_df['Sleep']+ data_df['Pain']

In [13]:
data_df.head(5)

,PID,PCL.score,PHQ.score,SDS.score,Days.Since,Reexp1,Reexp2,Avoid1,Avoid2,NACM1,...,Avoid2_cum,NACM1_cum,NACM2_cum,AAR1_cum,AAR2_cum,Sleep_cum,Pain_cum,Threshold,Nan_count,symptom_sum
1,202,25.0,7.0,0.0,2.0,2.0,2.500000,3.00,3.000,2.00,...,3.000000,2.000000,0.0000,0.0,0.500000,0.500000,5.500000,1,0,19.000000
2,202,25.0,7.0,0.0,5.5,1.0,1.250000,0.75,1.125,1.50,...,2.062500,1.750000,0.3750,0.0,0.250000,0.625000,4.750000,1,0,11.125000
3,202,25.0,7.0,0.0,9.5,0.0,0.500000,0.75,1.000,0.75,...,1.708333,1.416667,0.2500,0.0,0.250000,0.833333,4.083333,1,0,7.250000
4,202,25.0,7.0,0.0,13.5,0.0,0.333333,0.00,0.000,0.00,...,1.281250,1.062500,0.1875,0.0,0.270833,0.625000,3.479167,1,0,2.333333
5,202,25.0,7.0,0.0,17.5,0.0,0.000000,0.00,0.000,0.00,...,1.025000,0.850000,0.1500,0.0,0.216667,0.500000,2.916667,1,0,0.666667