In [16]:
import pandas as pd
import numpy as np

In [17]:
data_df = pd.read_csv('reduced.csv')

In [18]:
#remove HR column as it is irrelevant
data_df.index = np.arange(1,len(data_df)+1)
data_df.drop(['HR'], inplace=True,axis=1)

In [ ]:
#add Nan count column that has count of total Nans in a row
data_df['Nan_count'] = data_df.isnull().sum(axis=1)

#add symptom sum column which is the sum of all non-Nan values in a row instance
#if nan values -1
#data_df.replace(-1,0,inplace=True)
data_df['symptom_sum'] =  data_df['Reexp1']+ data_df['Reexp2']+data_df['Avoid1']+ data_df['Avoid2']+ data_df['NACM1']+ data_df['NACM2']+ data_df['AAR1']+ data_df['AAR2']+ data_df['Sleep']+ data_df['Pain']

In [19]:
#Adding a new column with the cumulative average of values: reexp1 till Pain
data_df.fillna(value=0, inplace=True)
data_df['Reexp1_cum'] =  data_df['Reexp1'].cumsum()
data_df['Reexp2_cum'] =  data_df['Reexp2'].cumsum()
data_df['Avoid1_cum'] =  data_df['Avoid1'].cumsum()
data_df['Avoid2_cum'] =  data_df['Avoid2'].cumsum()
data_df['NACM1_cum'] =  data_df['NACM1'].cumsum()
data_df['NACM2_cum'] =  data_df['NACM2'].cumsum()
data_df['AAR1_cum'] =  data_df['AAR1'].cumsum()
data_df['AAR2_cum'] =  data_df['AAR2'].cumsum()
data_df['Sleep_cum'] =  data_df['Sleep'].cumsum()
data_df['Pain_cum'] =  data_df['Pain'].cumsum()

In [21]:
c=1;
while(c!=1144):
    i1 = data_df.get_value(c, 'Reexp1_cum', takeable=False)
    data_df.set_value(c, 'Reexp1_cum',i1/c)
    
    i2 = data_df.get_value(c, 'Reexp2_cum', takeable=False)
    data_df.set_value(c, 'Reexp2_cum',i2/c)
    
    i3 = data_df.get_value(c, 'Avoid1_cum', takeable=False)
    data_df.set_value(c, 'Avoid1_cum',i3/c)
    
    
    i4 = data_df.get_value(c, 'Avoid2_cum', takeable=False)
    data_df.set_value(c, 'Avoid2_cum',i4/c)
    
    i5 = data_df.get_value(c, 'NACM1_cum', takeable=False)
    data_df.set_value(c, 'NACM1_cum',i5/c)
    
    i6 = data_df.get_value(c, 'NACM2_cum', takeable=False)
    data_df.set_value(c, 'NACM2_cum',i6/c)
    
    i7 = data_df.get_value(c, 'AAR1_cum', takeable=False)
    data_df.set_value(c, 'AAR1_cum',i7/c)
    
    i8 = data_df.get_value(c, 'AAR2_cum', takeable=False)
    data_df.set_value(c, 'AAR2_cum',i8/c)
    
    i9 = data_df.get_value(c, 'Sleep_cum', takeable=False)
    data_df.set_value(c, 'Sleep_cum',i9/c)
    
    i10 = data_df.get_value(c, 'Pain_cum', takeable=False)
    data_df.set_value(c, 'Pain_cum',i10/c)
    
   
    c = c+1

In [22]:
data_df.head()

,PID,Unnamed: 0.1,PCL.score,PHQ.score,SDS.score,Days.Since,Reexp1,Reexp2,Avoid1,Avoid2,...,Reexp1_cum,Reexp2_cum,Avoid1_cum,Avoid2_cum,NACM1_cum,NACM2_cum,AAR1_cum,AAR2_cum,Sleep_cum,Pain_cum
1,202,202.2000,25.0,7.0,0.0,2.0,2.0,2.500000,3.00,3.000,...,2.00,2.500000,3.000,3.000000,2.000000,0.0000,0.0,0.500000,0.500000,5.500000
2,202,202.5500,25.0,7.0,0.0,5.5,1.0,1.250000,0.75,1.125,...,1.50,1.875000,1.875,2.062500,1.750000,0.3750,0.0,0.250000,0.625000,4.750000
3,202,202.4775,25.0,7.0,0.0,9.5,0.0,0.500000,0.75,1.000,...,1.00,1.416667,1.500,1.708333,1.416667,0.2500,0.0,0.250000,0.833333,4.083333
4,202,202.1350,25.0,7.0,0.0,13.5,0.0,0.333333,0.00,0.000,...,0.75,1.145833,1.125,1.281250,1.062500,0.1875,0.0,0.270833,0.625000,3.479167
5,202,202.1750,25.0,7.0,0.0,17.5,0.0,0.000000,0.00,0.000,...,0.60,0.916667,0.900,1.025000,0.850000,0.1500,0.0,0.216667,0.500000,2.916667

In [ ]:
data_df1.index = np.arange(1,len(data_df)+1)

In [28]:
#Create a Threshold column which has value 0/1 which means either PTSD or not
data_df1['Threshold'] = 0
data_df1.head()

,PID,Unnamed: 0.1,PCL.score,PHQ.score,SDS.score,Days.Since,Reexp1,Reexp2,Avoid1,Avoid2,...,Reexp2_cum,Avoid1_cum,Avoid2_cum,NACM1_cum,NACM2_cum,AAR1_cum,AAR2_cum,Sleep_cum,Pain_cum,Threshold
1,202,202.2000,25.0,7.0,0.0,2.0,2.0,2.500000,3.00,3.000,...,2.500000,3.000,3.000000,2.000000,0.0000,0.0,0.500000,0.500000,5.500000,0
2,202,202.5500,25.0,7.0,0.0,5.5,1.0,1.250000,0.75,1.125,...,1.875000,1.875,2.062500,1.750000,0.3750,0.0,0.250000,0.625000,4.750000,0
3,202,202.4775,25.0,7.0,0.0,9.5,0.0,0.500000,0.75,1.000,...,1.416667,1.500,1.708333,1.416667,0.2500,0.0,0.250000,0.833333,4.083333,0
4,202,202.1350,25.0,7.0,0.0,13.5,0.0,0.333333,0.00,0.000,...,1.145833,1.125,1.281250,1.062500,0.1875,0.0,0.270833,0.625000,3.479167,0
5,202,202.1750,25.0,7.0,0.0,17.5,0.0,0.000000,0.00,0.000,...,0.916667,0.900,1.025000,0.850000,0.1500,0.0,0.216667,0.500000,2.916667,0

In [29]:
c=1;
while(c!=1144):
    th = data_df1.get_value(c, 'PCL.score', takeable=False)
    data_df1.set_value(c, 'Threshold',th > 10)
    c = c+1

In [30]:
data_df1.head()

,PID,Unnamed: 0.1,PCL.score,PHQ.score,SDS.score,Days.Since,Reexp1,Reexp2,Avoid1,Avoid2,...,Reexp2_cum,Avoid1_cum,Avoid2_cum,NACM1_cum,NACM2_cum,AAR1_cum,AAR2_cum,Sleep_cum,Pain_cum,Threshold
1,202,202.2000,25.0,7.0,0.0,2.0,2.0,2.500000,3.00,3.000,...,2.500000,3.000,3.000000,2.000000,0.0000,0.0,0.500000,0.500000,5.500000,1
2,202,202.5500,25.0,7.0,0.0,5.5,1.0,1.250000,0.75,1.125,...,1.875000,1.875,2.062500,1.750000,0.3750,0.0,0.250000,0.625000,4.750000,1
3,202,202.4775,25.0,7.0,0.0,9.5,0.0,0.500000,0.75,1.000,...,1.416667,1.500,1.708333,1.416667,0.2500,0.0,0.250000,0.833333,4.083333,1
4,202,202.1350,25.0,7.0,0.0,13.5,0.0,0.333333,0.00,0.000,...,1.145833,1.125,1.281250,1.062500,0.1875,0.0,0.270833,0.625000,3.479167,1
5,202,202.1750,25.0,7.0,0.0,17.5,0.0,0.000000,0.00,0.000,...,0.916667,0.900,1.025000,0.850000,0.1500,0.0,0.216667,0.500000,2.916667,1

In [31]:
data_df1.to_csv('reduced_new1.csv',index=False)